<div class="right">
  <div class="blue_tittle">Dispute Resolution</div>
  <div class="p_content">
    <p>
      <span>1. Prelude</span><br>
        &nbsp;&nbsp;Dindin, more specifically its websitewww.dindin.com, is an overseas online shopping platform founded on the basis oftrustworthiness and service excellence, and the same is expected from itsmerchants. We value merchants who comprehend and adhere to this philosophy, and assist them in any way we can.Upon the utilization of our services, it is acknowledged that merchants and buyers both agree that Dindin has the right to resolve disputes, howeverDindin is not a judiciary body, and thuscertain capabilities may be somewhat limited. Dindin shall resolve disputes upon request, however, Dindin shall not be held liable should the outcome not be up to expectation, as resolving of disputes can’t be guaranteed.All in all, Dindinshall provide assistance in certain aspects to help merchants and buyers reach a mutual agreement to avoid further conflict.<br></p>
     <p>
      <span>2. Dispute Resolution Principles</span><br>
      &nbsp;&nbsp;  1. Risks during delivery. Damages to cargo and the risk of loss shall be borne by the consignor before its receipt by consignee, and shall be borne by consignee after its receipt by consignee, except in the following circumstances.<br>
   &nbsp;&nbsp; a.Required by law;<br>
   &nbsp;&nbsp; b. Otherwise agreed by both parties; <br>
   &nbsp;&nbsp; c.Stated in the "Product Description"by merchants that the consignee’s identification documents must be produced for customs clearance. If the merchandise fails to clear customs or the clearance is delayed due to buyers failing to provide his or hervalid identification document, the loss shall be borne by the buyers. If merchants fail to state the aforementioned in the "Product Description", the loss shall be borne by the merchants.<br>
   &nbsp;&nbsp; In the eventthat the goods are deemed damagedor lostduring the point where the logistic companies are held liable, the consignor shall bear the loss in accordance with these rules.<br>
  &nbsp;&nbsp;The delivery location,in the event of return of goods, shall be the address established by the merchants.<br>
   &nbsp;&nbsp; 2. Delivery: Unless regulated by law or otherwise agreed by the both parties, if merchantsfail to deliver the purchased merchandises within the agreed upon period, which leads to buyers requesting for refunds, the orderswill then be deemed canceled.In the event that the merchandises are delivered after the agreed upon period, and buyers have requested for refunds prior to the receipt of the merchandises and after the agreed upon period, and merchants are aware of the request for refund yet chooses to deliver the merchandises thereafter, buyers are entitled to refuse to accept the merchandises upon delivery, and any losses arising from the abovementioned will be fully borne by the merchants, as well as providing the proof of delivery to Dindin. Unless otherwise agreed by both parties, charges incurred for logistics will not be on a Cash on Delivery method.<br>
   &nbsp;&nbsp; 3.Acceptance of merchandises: Upon delivery, merchandisesthat are accurately adequate in a physical manner, for avoidance of doubt the condition of the merchandises and its consistency with its descriptionscan be determined with the naked eye or with simple means of measurement tools to ascertain the authenticity of the merchandises, including but not limited to shape, size, weight, color, model and age, can be immediately accepted, or can be accepted within 3 days in the event that the consignee requires to evaluate the merchandisesupon receipt. In the event that the receipt issued upon delivery clearly indicates the hour of delivery, hence the evaluation period of 72 hours shall commence based on the hour indicated, however, in the event that the receipt issued upon delivery indicates the date of delivery without the hour of delivery, hence the evaluation period of 72 hours shall commence from zero hour of the following day upon the receipt of the merchandises. The consignee, or the delivery company,shallacknowledge the condition of the merchandises on its purchase orders or receipts.<br>
    Authenticationonphysical adequacy: When the merchandises are delivered to the consignees, the consignees shall confirm its consistency. For merchandises that are delivered to the consignees, the consignees shall sign and accept the merchandises as acknowledgement. In the eventthat a third party is commissioned to accept the merchandises, the third party shall provide its identification documents together with the authorization documents of the consignee and the identification documents of the consignee.<br>
    For deliveries that require signatures upon receipt of merchandises, consignees shall require the logistics company representative assigned as a witness upon receipt and merchandise packaging opening. In the event that there should be any inconsistencies based on the merchandises received and its physical adequacy as described above, consignees are entitled to reject the merchandises and have the reason of rejection clearly stated on the receipts with the acknowledgement signature of the logistics company representative. In the event that consignees have acknowledge the receipt of the merchandises and its physical adequacies, consignees will subsequently not be entitledto dispute over any matter arising thereof or request for any refund or financial compensation, unless consignees are able to provide verifiable evidence that indicates foul play.<br>
   &nbsp;&nbsp; 4. Return Policy: In the eventthat buyerswould like to request to have the merchandises returned, the requests must be made within 7 days upon receipt of the merchandises. In the event that the receipt issued upon delivery clearly indicates the hour of delivery, hence the request period of 168 hours shall commence based on the hour indicated, however, in the event that the receipt issued upon delivery indicates the date of delivery without the hour of delivery, hence the request period of 168 hours shall commence from zero hour of the following day upon the receipt of the merchandises. In the event that the request period has exceeded and merchants refuse to acknowledge the request of return of the merchandises, Dindin has the right to award the disputed amount to the buyers, and buyers will henceforth be in agreement with Dindin and shall successfully return the merchandises with acknowledgement of receipt of the merchandises by the merchants within the agreed upon period to be refunded the disputed amount. In the event that the buyers fail to return the merchandises within the agreed upon period, the dispute will be deemed invalid and no amount shall be refunded to the buyers, and Dindin has the right to award the transacted amount to the merchants. Furthermore, merchants shall fulfill its obligations and provide accurate return addresses for the purpose of return of merchandises. In the event that merchants fail to provide accurate return addresses, Dindin has the right to refund the transacted amount to the buyers, and no amount shall be awarded to the merchants.<br>
   Upon ascertaining an agreement between merchants and buyers, however both parties fail to reach an agreement on costs of logistics, the costs shall be borne by the merchants. In the event that merchants agree to accept the merchandises to be returned or exchanged but not to any costs involving logistics, the buyers are obligated to successfully return the merchandises to the merchants, and upon receipt of the merchandises by the merchants, Dindin shall resolve the dispute of the party liable for the logistics costs. Unless expressly agreed by both parties, the logistics fees cannot be paid on aCash on Delivery method. In the event that the merchandises are returned due to the fault of the merchants, the merchants shall bear the logistics costs.If the merchant refuses to do so, Dindin has the right to proceed with necessary actions, including but not limited to, freezing of the merchants’ accounts and discontinuing services provided to the merchants. Under other conditions, the logistics costs shall be borne by the buyers, unless in the conditions hereafter:<br>
    &nbsp;&nbsp;    a.Return of merchandises are carried out as agreed by both parties. No amendments can be done upon reaching the agreement.<br>
     &nbsp;&nbsp;   b. The buyers shall have the merchandisesremain intact during returning the merchandises, in order to not affect the secondary sale, including full and complete structures, functions, values and accessories. In the event that the buyers fail to adhere, the buyers shall be held accountable.<br>
     &nbsp;&nbsp;   c. For any damages or losses incurred during the process of the return of the merchandises due to the fault of the logistics companies, the consignee shall contact the consigner, and bear the costs for losses (if any).<br>
     &nbsp;&nbsp;    d.Fluctuations to the market prices of the merchandises due to market factors cannot be reasons for return of merchandises. The transaction price stated on the transaction page shall be executed.<br>
    &nbsp;&nbsp;  5. Identity verification: In the event of disputes, Dindin has the right to require the identification documents of both parties. In the eventthat either party refuses to do so, any proof provided by the refusing party will not be acknowledged.<br>
      &nbsp;&nbsp;6. Payment from disputes: In the event that any of the following conditions are met, both parties agree that Dindinremit payment:<br>
      Upon dispute arising, both parties agree that Dindin has the right to remit the partial or entire disputed amount to one or both parties, according to the materials or evidences provided by both parties. In the event that additional conditions arises that is not clearly stated in this article, both parties authorizesDindin to decide based on its own discretion.<br>
   In the eventthat both parties clearly inform Dindin of its decision to resolve the disputes through negotiation or legal channels, Dindinshall retain the disputed amount and suspend the dispute settlement procedures. Based on the negotiations, Dindin shallremit the partial or entire disputed amount to one or both parties, or based on the decisions of the court or public security body. In the event that Dindin does not receive the negotiation results or decisions from the court or public security body within 30 days from the date of the dispute arising, or the court or public security body has not filed the case within 7 days or has not made any decisions six months after filing the case, Dindin has the right to return the amount to the buyer or the merchant based on its discretion. <br>
     In the eventthat both parties agree to resolve the disputesthrough negotiations, the merchandises shall be returned within 90 days commencing from the day the agreement is agreed on. Contrarily, Dindin has the right to remit the partial or entire disputed amount to one or both parties at its discretion. In the event that Dindin has finalized the decision that the reason of the return of the merchandises is due to fault of the merchants, hence the depreciation risk shall be borne by the merchants. In the eventthat the reason of the return of the merchandises is due to the fault of the buyers, the depreciation risk shall be borne by the buyers. In the event that Dindinrequests for the buyers to return the merchandises, and the buyers fail to do so within the requested period, or after both parties have agreed to the return of the merchandises but the buyers fails to do so within the requested period, the buyers shall bear the depreciation risk. In the event that the buyers refuse to return the merchandises, Dindin reserves the right to remit the disputed amount to the merchant.<br>
    &nbsp;&nbsp;7. Sales of prohibited items: Merchants are prohibited from selling merchandises banned by the law on the website of Dindin, more specifically www.dindin.com. In the event that the buyers lodge a complaints to Dindinpertaining to receiving prohibited merchandises, and is verified by Dindin to be true, the merchants must accept the return of the merchandises, and bear the all costs arising thereof. Subsequently, the merchantsshall be liable to the penalties deemed reasonable by Dindin and the laws of the country. In the event that both parties deliberately perform transactions involving prohibited merchandises and should any dispute arise thereafter, Dindinreserves the right to manage the disputed amount according to the Return Policy.<br>
   &nbsp;&nbsp; 8. Pertaining to disputes that may involve postage fees, in order to prevent further disputes, in the event that there should be a disagreement on the postage fee, the buyers shall negotiate with the merchantsprior to remitting payments, in order for the merchantsto adjust the prices accordingly should the merchants agree to do so. Upon remitting payments, the buyers accept and acknowledge payment of the postage fees by default, thusDindin will not entertain any complaints arising thereof.<br>
     </p>
     
     <p><span>3. Determination of merchandises’ quality</span><br>
      &nbsp;&nbsp; 1. Criteria of "product description"<br>
   &nbsp;&nbsp; The "product description" should cover the appearance, composition, contents, mass, age, packaging, warranty, effective date, after-sales services, origin, manufacturer and other essential elements.<br>
   &nbsp;&nbsp; In the event that it is not explicitly stated in the "product description", hence the national standards, industry standards or vendor standards shall prevail, and it shall be deemed that both parties agree.<br>
  &nbsp;&nbsp;  In the event that the merchandisesare flawed, the flaw must be described in the "product description", failure to do so will lead to the merchandisesbeing deemed flawless.<br>
   &nbsp;&nbsp; In the event that both parties have reached an agreement regarding changes to the "product description", the party that objects thereafter must provide adequate and accurate evidence to prove otherwise. <br>
   &nbsp;&nbsp; Descriptions such as"for detailed descriptions, please click on the link http: // ******" is considered invalid. Descriptions obtained from other sites shall not be used as a replacement for the "product description" onDindin’s website, more specificallywww.dindin.com.<br>
   &nbsp;&nbsp; In the event that the buyers receivethe merchandises that are inconsistent with the "product description", however both parties do not disputeon the matter, hence the transactionsshall be deemed valid and undisputed.<br>
   &nbsp;&nbsp; For the appearance, composition, content, quality, packaging, warranty, age, shelf life, after-sales service, place of origin, trade names and other descriptions of the merchandises, the "product description" on the website of Dindin,www.dindin.com, on the date of transaction shall prevail.<br>
  &nbsp;&nbsp;  2. The merchants shall bear the burden of proving the accuracy of the product descriptions, by providing documents including but not limited to, manufacturer certifications, product certifications, official invoices and other relevant documents.<br>
  &nbsp;&nbsp;  3. For matters of quality pertaining to merchandises that cannot be determined from its appearances, proof from the Administration of Quality Supervision, or from the corresponding brand service center shall be required.<br>
   &nbsp;&nbsp; 4. For disputes arising from unclear agreements, in the event that the transactions are canceled, the lossesshall be borne by both parties, but the ratio shall be decided by Dindinon a case to case basis at its discretion.<br>
   &nbsp;&nbsp; 5. Pre-owned merchandises<br>
  &nbsp;&nbsp;  Defective merchandises: The product description shall be taken into account to determine the defectiveness of the merchandises and evidences of the verification shall be provided to Dindin. In the event that the objecting party fails to provide the necessary evidences, or the cost that may incur to provide such evidences may be higher than the disputed amount, the preceding paragraph shall take effect.
    &nbsp;&nbsp;For users of Dindin prior to the implementation of this policy, the policy applicable at the point of registration shall be practiced. For users of Dindin after the implementation of this policy, the abovementioned policy applies.<br>
   &nbsp;&nbsp; Dindinreserves the final rights of interpretation of the above provisions.<br>
      
     </p>
  </div>
  <div class="space_a"></div>
  </div>